---
booktitle: Proceedings of The 4th International Conference on Predictive Applications
  and APIs
shortname: PAPIs
year: '2017'
volume: 82
start: 2016-10-24
end: 2016-10-25
url: http://proceedings.mlr.press
published: 2018-08-09
layout: proceedings
series: Proceedings of Machine Learning Research
id: PAPIs-2016
month: 0
cycles: false
editor:
- given: Claire
  family: Hardgrove
- given: Louis
  family: Dorard
- given: Keiran
  family: Thompson
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 4th International Conference on Predictive Applications and APIs
    Held in Microsoft NERD, Boston, USA on 24-25 October 2016

  Published as Volume 82 by the Proceedings of Machine Learning Research on 09 August 2018.

  Volume Edited by:
    Claire Hardgrove
    Louis Dorard
    Keiran Thompson

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 24--25 Oct
baseurl: "/v82"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v82
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: International Conference on Predictive Applications and APIs
  url: 
  location: Microsoft NERD, Boston, USA
  dates:
  - 2016-10-24
  - 2016-10-25
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from /Users/mreid/mlresearch/v82/papis2017-boston.bib
